version: '2.3'

services:

  the-service:
    image: microsoft/vscode-bug-with-remote-containers-and-environment-variables
    build:
      dockerfile: ./dockerfiles/Dockerfile
      context: .
      args:
        VSCODE_ENV_VAR_TEST: ${VSCODE_ENV_VAR_TEST}
    environment:
      VSCODE_ENV_VAR_TEST: ${VSCODE_ENV_VAR_TEST}
